service:
  name: userAPI

plugins:
- serverless-webpack

provider:
  name: aws
  profile: inventaweb
  runtime: nodejs8.10
  region: us-east-2
  stage: dev
  environment:
    MYSQL_HOST: ${file(env.yml):MYSQL_HOST}
    MYSQL_DATABASE: ${file(env.yml):MYSQL_DATABASE}
    MYSQL_USER: ${file(env.yml):MYSQL_USER}
    MYSQL_PASS: ${file(env.yml):MYSQL_PASS}
    JWT_KEY: ${file(env.yml):JWT_KEY}
    JWT_TIME: ${file(env.yml):JWT_TIME}
    SALT: ${file(env.yml):SALT}

functions:
  # User Routes
  userGet:
    handler: models/user.get
    memorySize: 128
    events:
    - http:
        method: get
        cors: true
        path: /user/{proxy+}
        authorizer:
          name: authFunc
          resultTtlInSeconds: 0 # This sets all of the ttl for auth to 0 seconds.  Since policy returned is specific to the call this is critical.
        request:
          parameters:
            paths:
              proxy: true
    - http:
        method: get
        cors: true
        path: /user
        authorizer:
          name: authFunc
          resultTtlInSeconds: 0 # This sets all of the ttl for auth to 0 seconds.  Since policy returned is specific to the call this is critical.
        request:
          parameters:
            paths:
              proxy: true

  userRegister:
    handler: models/user.register
    memorySize: 128
    events:
    - http:
        method: post
        cors: true
        path: /user/register

  userAuth:
    handler: models/user.authUser
    memorySize: 128
    events:
    - http:
        method: post
        cors: true
        path: /user/auth

  userPost:
    handler: models/user.post
    memorySize: 128
    events:
    - http:
        method: post
        cors: true
        path: /user/{proxy+}
        authorizer:
          name: authFunc
          resultTtlInSeconds: 0 # This sets all of the ttl for auth to 0 seconds.  Since policy returned is specific to the call this is critical.
        request:
          parameters:
            paths:
              proxy: true
    - http:
        method: post
        cors: true
        path: /user
        authorizer:
          name: authFunc
          resultTtlInSeconds: 0 # This sets all of the ttl for auth to 0 seconds.  Since policy returned is specific to the call this is critical.

  userPut:
    handler: models/user.put
    memorySize: 128
    events:
    - http:
        method: put
        cors: true
        path: /user/{proxy+}
        authorizer:
          name: authFunc
          resultTtlInSeconds: 0 # This sets all of the ttl for auth to 0 seconds.  Since policy returned is specific to the call this is critical.
        request:
          parameters:
            paths:
              proxy: true
    - http:
        method: put
        cors: true
        path: /user
        authorizer:
          name: authFunc
          resultTtlInSeconds: 0 # This sets all of the ttl for auth to 0 seconds.  Since policy returned is specific to the call this is critical.
        request:
          parameters:
            paths:
              proxy: true

  userDelete:
    handler: models/user.del
    memorySize: 128
    events:
    - http:
        method: delete
        cors: true
        path: /user/{proxy+}
        authorizer:
          name: authFunc
          resultTtlInSeconds: 0 # This sets all of the ttl for auth to 0 seconds.  Since policy returned is specific to the call this is critical.
        request:
          parameters:
            paths:
              proxy: true
    - http:
        method: delete
        cors: true
        path: /user
        authorizer:
          name: authFunc
          resultTtlInSeconds: 0 # This sets all of the ttl for auth to 0 seconds.  Since policy returned is specific to the call this is critical.
        request:
          parameters:
            paths:
              proxy: true


  # Schedule Routes
  scheduleGet:
    handler: models/schedule.get
    memorySize: 128
    events:
      - http:
          method: get
          cors: true
          path: /schedule/{proxy+}
          authorizer:
            name: authFunc
            resultTtlInSeconds: 0 # This sets all of the ttl for auth to 0 seconds.  Since policy returned is specific to the call this is critical.
          request:
            parameters:
              paths:
                proxy: true
      - http:
          method: get
          cors: true
          path: /schedule
          authorizer:
            name: authFunc
            resultTtlInSeconds: 0 # This sets all of the ttl for auth to 0 seconds.  Since policy returned is specific to the call this is critical.
          request:
            parameters:
              paths:
                proxy: true

  schedulePost:
    handler: models/schedule.post
    memorySize: 128
    events:
      - http:
          method: post
          cors: true
          path: /schedule/{proxy+}
          authorizer:
            name: authFunc
            resultTtlInSeconds: 0 # This sets all of the ttl for auth to 0 seconds.  Since policy returned is specific to the call this is critical.
          request:
            parameters:
              paths:
                proxy: true
      - http:
          method: post
          cors: true
          path: /schedule
          authorizer:
            name: authFunc
            resultTtlInSeconds: 0 # This sets all of the ttl for auth to 0 seconds.  Since policy returned is specific to the call this is critical.
          request:
            parameters:
              paths:
                proxy: true

  schedulePut:
    handler: models/schedule.put
    memorySize: 128
    events:
      - http:
          method: put
          cors: true
          path: /schedule/{proxy+}
          authorizer:
            name: authFunc
            resultTtlInSeconds: 0 # This sets all of the ttl for auth to 0 seconds.  Since policy returned is specific to the call this is critical.
          request:
            parameters:
              paths:
                proxy: true
      - http:
          method: put
          cors: true
          path: /schedule
          authorizer:
            name: authFunc
            resultTtlInSeconds: 0 # This sets all of the ttl for auth to 0 seconds.  Since policy returned is specific to the call this is critical.
          request:
            parameters:
              paths:
                proxy: true

  scheduleDelete:
    handler: models/schedule.del
    memorySize: 128
    events:
      - http:
          method: delete
          cors: true
          path: /schedule/{proxy+}
          authorizer:
            name: authFunc
            resultTtlInSeconds: 0 # This sets all of the ttl for auth to 0 seconds.  Since policy returned is specific to the call this is critical.
          request:
            parameters:
              paths:
                proxy: true
      - http:
          method: delete
          cors: true
          path: /schedule
          authorizer:
            name: authFunc
            resultTtlInSeconds: 0 # This sets all of the ttl for auth to 0 seconds.  Since policy returned is specific to the call this is critical.
          request:
            parameters:
              paths:
                proxy: true


  # Settings Routes
  settingsGet:
    handler: models/settings.get
    memorySize: 128
    events:
    - http:
        method: get
        cors: true
        path: /settings/{proxy+}
        authorizer:
          name: authFunc
          resultTtlInSeconds: 0 # This sets all of the ttl for auth to 0 seconds.  Since policy returned is specific to the call this is critical.
        request:
          parameters:
            paths:
              proxy: true
    - http:
        method: get
        cors: true
        path: /settings
        authorizer:
          name: authFunc
          resultTtlInSeconds: 0 # This sets all of the ttl for auth to 0 seconds.  Since policy returned is specific to the call this is critical.
        request:
          parameters:
            paths:
              proxy: true

  settingsPut:
    handler: models/settings.put
    memorySize: 128
    events:
    - http:
        method: put
        cors: true
        path: /settings/{proxy+}
        authorizer:
          name: authFunc
          resultTtlInSeconds: 0 # This sets all of the ttl for auth to 0 seconds.  Since policy returned is specific to the call this is critical.
        request:
          parameters:
            paths:
              proxy: true
    - http:
        method: put
        cors: true
        path: /settings
        authorizer:
          name: authFunc
          resultTtlInSeconds: 0 # This sets all of the ttl for auth to 0 seconds.  Since policy returned is specific to the call this is critical.
        request:
          parameters:
            paths:
              proxy: true

  #Auth

  authFunc:
    handler: models/auth.authorize
    memorySize: 128

resources:
  Resources:
    GatewayResponse:
      Type: AWS::ApiGateway::GatewayResponse
      Properties:
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
          gatewayresponse.header.Access-Control-Allow-Headers: "'*'"
        ResponseType: EXPIRED_TOKEN
        RestApiId:
          Ref: ApiGatewayRestApi
        StatusCode: '401'
    AuthFailureGatewayResponse:
      Type: AWS::ApiGateway::GatewayResponse
      Properties:
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
          gatewayresponse.header.Access-Control-Allow-Headers: "'*'"
        ResponseType: UNAUTHORIZED
        RestApiId:
          Ref: ApiGatewayRestApi
        StatusCode: '401'
